version: "3.3"


services:

  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./static:/app/static
      - ./uploads:/app/uploads
      - ./thumbnails/uploads:/app/thumbnails/uploads
    depends_on:
      - web
    restart: "on-failure"
  
  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file: 
      - .env
    restart: "on-failure"
  
  web:
    build: .
    command: >
      sh -c "python3 manage.py makemigrations users &&
             python3 manage.py makemigrations files &&
             python3 manage.py migrate &&
             python3 manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - ./static:/app/static
    env_file: 
      - .env
    expose:
      - "8000"
    restart: "on-failure"
    depends_on:
      - db
    
  redis:
    image: redis:6.2.6
    ports:
      - "6379:6379"
    depends_on:
      - web
  
  celery:
    build: .
    command: celery -A config worker -l INFO
    volumes:
      - .:/app
      - ./static:/app/static
    env_file: 
      - .env
    restart: "on-failure"
    depends_on:
      - redis
      - web